import { assetPath } from "@/lib/site";
import Image from "next/image";
import Link from "next/link";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";

export const metadata = { title: "Über SitSanus", description: "SitSanus: Ergonomisches Denken, Entwicklung und Produktion aus Frankfurt am Main." };

export default function AboutPage() { return <><Header /><main className="about">
  <section className="about-hero"><div className="shell about-hero-grid"><div><p className="eyebrow">Frankfurt am Main</p><h1>Mitten in Deutschland.<br /><em>Nah an deinem Alltag.</em></h1><p className="lead">SitSanus entsteht in Frankfurt: von der Idee über die Auswahl bis zur sorgfältigen Produktion ergonomischer Arbeitsplatzausstattung.</p></div><figure className="about-hero-image"><Image src={assetPath("/images/frankfurt-studio.webp")} alt="Helle SitSanus Werkstatt und Designstudio in Frankfurt" fill sizes="(max-width: 760px) 100vw, 43vw" priority /><figcaption>Entwicklung & Produktion<br />Frankfurt am Main</figcaption></figure></div></section>
  <section className="about-story"><div className="shell about-grid"><div><p className="eyebrow">Unsere Haltung</p><h2>Wir machen Arbeit am Bildschirm menschlicher.</h2></div><div className="about-copy"><p>Ein guter Arbeitsplatz ist kein Statussymbol. Er ist eine tägliche Unterstützung – besonders dann, wenn der Kalender voll ist und der Kopf viel leistet.</p><p>Darum verbinden wir funktionales Produktwissen mit verständlicher Beratung. In Frankfurt entwickeln und produzieren wir mit kurzen Wegen, klaren Maßstäben und einem Blick fürs Wesentliche.</p><div className="location-note"><span aria-hidden>●</span><p><strong>Frankfurt am Main</strong>zentral gelegen, bewusst lokal gedacht.</p></div></div></div></section>
  <section className="founder"><div className="shell founder-grid"><div className="founder-image"><Image src={assetPath("/images/dennis-boehm.webp")} alt="Dennis Böhm, Geschäftsführer von SitSanus" fill sizes="(max-width: 760px) 100vw, 42vw" priority /></div><div className="founder-copy"><p className="eyebrow">Hinter SitSanus</p><h2>Dennis Böhm</h2><p className="founder-role">Geschäftsführer · Experte für IT & Ergonomie</p><p>„Technik soll Menschen unterstützen – nicht verlangen, dass sie sich ihr anpassen. Genau mit diesem Gedanken ist SitSanus entstanden.“</p><p>Mit seinem Hintergrund in IT und seinem Blick für echte Alltagstauglichkeit bringt Dennis die beiden Seiten eines guten Arbeitsplatzes zusammen: kluge Technik und einen Körper, der sich wohlfühlt.</p></div></div></section>
  <section className="made-here"><div className="shell"><p className="eyebrow centered">Aus Frankfurt</p><h2 className="centered">Nicht irgendwo gedacht.<br />Hier sorgfältig gemacht.</h2><div className="made-grid"><p><strong>Kurze Wege</strong>Entwicklung, Abstimmung und Produktion bleiben so nah wie möglich beieinander.</p><p><strong>Klare Auswahl</strong>Wir setzen auf nachvollziehbare Funktion statt auf laute Schlagworte.</p><p><strong>Für lange Tage</strong>Jede Entscheidung soll sich im Alltag bewähren – an jedem Schreibtisch.</p></div></div></section>
  <section className="wink"><div className="shell wink-grid"><div className="wink-image"><Image src={assetPath("/images/dennis-und-john-wick.webp")} alt="Dennis Böhm mit John Wick bei einer Veranstaltung" fill sizes="(max-width: 760px) 100vw, 50vw" /></div><div><p className="eyebrow">Ein kleiner Seitenhieb</p><h2>John Wick würde für unsere Stühle töten.</h2><p>Zum Glück reicht uns dein gutes Sitzgefühl. Aber bei Qualität verstehen wir den Einsatz.</p><small>Augenzwinkernder Fan-Moment – keine offizielle Verbindung zur Filmreihe.</small></div></div></section>
  <section className="closing"><div className="shell closing-inner"><p className="eyebrow">Lerne uns kennen</p><h2>Erst verstehen.<br /><em>Dann besser arbeiten.</em></h2><p>Finde mit unserem kostenlosen Leitfaden heraus, was dein Arbeitsplatz wirklich braucht.</p><Link className="button button-cream" href="/leitfaden">Zum Leitfaden <span>→</span></Link></div></section>
</main><Footer /></>; }
