export const metadata = { title: "Kampagne: Ziele & Auswertung", alternates: { canonical: "/marketing-zentrale/nachhaltigkeitskampagne/auswertung/" } };
const risks = [
  ["Greenwashing", "Konkrete Belege statt pauschaler Umweltversprechen. Ungeprüfte Herkunfts- und Produkteigenschaften zuerst verifizieren."],
  ["Verkauf versus Weiterverwendung", "Auch der Verzicht auf einen Neukauf ist ein gutes Beratungsergebnis; keine Kaufpflicht für den Check."],
  ["Unklare Serviceversprechen", "Reparatur und Ersatzteile pro Produkt prüfen. Geplante Leistungen von bestehenden Angeboten unterscheiden."],
  ["Kritische Kommentare", "Sachlich antworten, Quellen nennen, Fehler sichtbar korrigieren und berechtigte Kritik nicht ausblenden."],
  ["Zu wenig Resonanz", "Ansprache und Angebot im kleinen Test prüfen; Budget gezielt einsetzen und Abweichungen offenlegen."],
  ["Zu viele Anfragen", "Beratungskapazität begrenzen, Wartezeiten nennen und Anzeigen bei ausgelasteten Terminen pausieren."],
  ["Messlücken", "Formular und Zuordnung vorab testen, Dubletten entfernen und nicht zuordenbare Anfragen separat ausweisen."],
];
export default function EvaluationPage() {
  return <><section className="campaign-intro"><p className="eyebrow">SMART-Ziel</p><h2>30 Beratungsanfragen.<br /><em>In acht Wochen.</em></h2><p>Innerhalb von acht Wochen sollen über Instagram mindestens 30 gültige Anfragen für den kostenlosen Arbeitsplatz-Check entstehen. Dafür sind 600 messbare Kampagnensitzungen und eine Anfrage-Conversion von mindestens 5 % vorgesehen.</p></section><div className="campaign-targets"><article><strong>30</strong><span>gültige Anfragen</span></article><article><strong>600</strong><span>messbare Sitzungen</span></article><article><strong>5 %</strong><span>Anfrage-Conversion</span></article></div><p className="campaign-caption">Zielwerte: 600 Sitzungen × 5 % Conversion = 30 Anfragen.</p><dl className="campaign-mix">{[
  ["Spezifisch", "Konkrete Anfragen für den Arbeitsplatz-Check gewinnen."],
  ["Messbar", "Gültige Anfragen und zugehörige Kampagnensitzungen erfassen; Spam, Tests und Dubletten ausschließen."],
  ["Attraktiv / akzeptiert", "Orientierung für Interessierte und Beratungskontakte für SitSanus; Beratungsumfang vorab im Team abstimmen."],
  ["Realistisch geplant", "600 € Anzeigenbudget bei angenommenen 1 € je messbarer Sitzung und Kapazität für rund vier Erstberatungen pro Woche. Im Pilot zu testen."],
  ["Terminiert", "Acht Wochen ab Start; Zwischenprüfungen nach Woche 2 und 4, Abschlussauswertung spätestens sieben Tage nach Ende."],
].map(([name, text]) => <div key={name}><dt><strong>{name}</strong></dt><dd>{text}</dd></div>)}</dl><section className="campaign-section"><p className="eyebrow">Drei KPIs</p><h2>Interesse. Handlung. Ergebnis.</h2><div className="campaign-grid campaign-kpis">{[
  ["≥ 1,5 %", "Outbound-Klickrate", "Ausgehende Linkklicks zur Kampagnenseite ÷ Anzeigenimpressionen × 100. Nur bezahlte Kampagnenanzeigen.", "Prüft, ob die Ansprache Interesse an weiteren Informationen auslöst."],
  ["≥ 5 %", "Anfrage-Conversion-Rate", "Gültige zugeordnete Anfragen ÷ messbare Instagram-Kampagnensitzungen × 100.", "Prüft, ob Interesse zur konkreten Kontaktaufnahme führt."],
  ["≥ 30", "Gültige Anfragen", "Eindeutige übermittelte Anfragen mit erreichbarem Kontakt und konkretem Anliegen. Ohne Spam, Tests und Dubletten.", "Misst unmittelbar das Kampagnenziel innerhalb von acht Wochen."],
].map(([value, name, formula, purpose]) => <article className="campaign-card" key={name}><span className="campaign-kpi-value">{value}</span><h3>{name}</h3><p>{formula}</p><p className="campaign-action">{purpose}</p></article>)}</div></section><aside className="campaign-note"><strong>So wird gemessen</strong><p>Anzeigenwerte kommen aus dem Meta Ads Manager. UTM-Links unterscheiden bezahlte und organische Instagram-Besuche. Eine Anfrage wird zugeordnet, wenn sie in einer gekennzeichneten Sitzung erfolgreich übermittelt und als gültig geprüft wurde. Maximal eine Conversion je Sitzung; wiederholte Kontakte werden bereinigt.</p><p>Zähler und Nenner betreffen dieselbe messbare Besuchsgruppe und denselben Zeitraum. Nicht zuordenbare Anfragen werden separat dokumentiert. Klicks sind nicht automatisch Sitzungen. </p></aside><section className="campaign-section"><p className="eyebrow">Risiken & Gegenmaßnahmen</p><h2>Vertrauen braucht Klarheit.</h2><div className="campaign-risks">{risks.map(([title, text]) => <details key={title}><summary>{title}</summary><p>{text}</p></details>)}</div></section><p className="campaign-caption">Quelle: <a href="https://www.umweltbundesamt.de/themen/gruene-waren-dienstleistungen-bewerben-so-gehts">Umweltbundesamt: Umweltvorteile glaubwürdig kommunizieren</a>.</p></>;
}
